name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code du dépôt
        uses: actions/checkout@v4

      - name: Configuration et compilation automatique Flet/Android
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          python-path: '.'
