name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code du depot
        uses: actions/checkout@v4

      - name: Configurer Java 17 (Requis pour Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer l'environnement de build Flet
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          python-path: '.'
